-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_PRICE
FROM BOOK A
JOIN AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES C
ON A.BOOK_ID = C.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 01
GROUP BY CATEGORY, A.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, CATEGORY DESC